# Generated by Django 5.0.6 on 2024-05-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthtest',
            options={'verbose_name': 'salud'},
        ),
    ]
